// Generated by CoffeeScript 1.8.0
var Idea, mongoose;

mongoose = require('mongoose');

Idea = new mongoose.Schema({
  listType: {
    type: String,
    "enum": ['unspecified', 'art/gallery', 'philanthropy', 'productivity']
  },
  body: String,
  datetime: {
    type: Date,
    "default": Date.now
  }
});

module.exports = mongoose.model('Idea', Idea);
