// Generated by CoffeeScript 1.8.0
var app, assets, bodyParser, config, cookieParser, env, express, ideas, mongoose, path, routes, session;

express = require('express');

path = require('path');

assets = require('connect-assets');

mongoose = require('mongoose');

session = require('express-session');

cookieParser = require('cookie-parser');

bodyParser = require("body-parser");

ideas = require('./controllers/ideas');

app = express();

app.port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

env = process.env.NODE_ENV || "development";

config = require("./config");

config.setEnvironment(env);

if (env !== 'production') {
  mongoose.connect('mongodb://localhost/example');
} else {
  console.log('If you are running in production, you may want to modify the mongoose connect path');
}

app.use(assets());

app.use(require('less-middleware')(path.join(__dirname, 'assets')));

app.use(express["static"](process.cwd() + '/public'));

console.log("setting session/cookie");

app.use(cookieParser());

app.use(session({
  secret: "keyboard cat",
  key: "sid",
  cookie: {
    secure: true
  }
}));

app.set('view engine', 'jade');

app.use(bodyParser());

routes = require('./routes');

routes(app);

module.exports = app;
