// Generated by CoffeeScript 1.8.0
var Idea;

Idea = require('../models/idea');

module.exports = {
  index: function(req, res) {
    return Idea.find({}, function(err, ideas) {
      return res.send(ideas);
    });
  },
  create: function(req, res) {
    var idea;
    idea = new Idea(req.body);
    return idea.save(function(err, idea) {
      if (!err) {
        res.send(idea);
        return res.statusCode = 201;
      } else {
        res.send(err);
        return res.statusCode = 500;
      }
    });
  },
  get: function(req, res) {
    return Idea.findById(req.params.id, function(err, idea) {
      if (!err) {
        return res.send(idea);
      } else {
        res.send(err);
        return res.statusCode = 500;
      }
    });
  },
  update: function(req, res) {
    return Idea.findByIdAndUpdate(req.params.id, {
      "$set": req.body
    }, function(err, idea) {
      if (!err) {
        return res.send(idea);
      } else {
        res.send(err);
        return res.statusCode = 500;
      }
    });
  },
  "delete": function(req, res) {
    return Idea.findByIdAndRemove(req.params.id, function(err) {
      if (!err) {
        return res.send({});
      } else {
        res.send(err);
        return res.statusCode = 500;
      }
    });
  }
};
