// Generated by CoffeeScript 1.8.0
module.exports = {
  index: function(req, res) {
    return res.send('This is a private page.');
  },
  create: function(req, res) {
    req.session.authorized = 'test';
    return res.redirect('/private');
  },
  destroy: function(req, res) {
    delete req.session.authorized;
    return res.redirect('/private');
  }
};
